services:
  app:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOST: db
      DATABASE_USER: jiujitsu_user
      DATABASE_PASSWORD: senha_forte_123
      DATABASE_NAME: academia_jiujitsu
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: sua_senha_root_aqui
      MARIADB_DATABASE: academia_jiujitsu
      MARIADB_USER: jiujitsu_user
      MARIADB_PASSWORD: senha_forte_123
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/backups:/docker-entrypoint-initdb.d/backups:ro
      - ./schema.sql:/docker-entrypoint-initdb.d/10_schema.sql:ro
      - ./data.sql:/docker-entrypoint-initdb.d/20_data.sql:ro

volumes:
  mariadb_data: {}
