# docker-compose.yml

services:
  app:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
    entrypoint: ["./docker-entrypoint.sh"]
    command: ["bundle", "exec", "ruby", "app.rb", "-o", "0.0.0.0"]
    environment:
      DATABASE_HOST: db
      DATABASE_USER: jiujitsu_user
      DATABASE_PASSWORD: senha_forte_123
      DATABASE_NAME: academia_jiujitsu_dev
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5433:5432" # <-- A CORREÇÃO ESTÁ AQUI!
    environment:
      POSTGRES_USER: jiujitsu_user
      POSTGRES_PASSWORD: senha_forte_123
      POSTGRES_DB: academia_jiujitsu_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data: {}