services:
  app:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
    entrypoint: ["./docker-entrypoint.sh"]
    command: ["bundle", "exec", "ruby", "app.rb", "-o", "0.0.0.0"]
    environment:
      DATABASE_HOST: db
      DATABASE_USER: jiujitsu_user
      DATABASE_PASSWORD: senha_forte_123
      DATABASE_NAME: academia_jiujitsu
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: sua_senha_root_aqui
      MARIADB_DATABASE: academia_jiujitsu
      MARIADB_USER: jiujitsu_user
      MARIADB_PASSWORD: senha_forte_123
    volumes:
      - mariadb_data:/var/lib/mysql
      # Monta a pasta inteira. Os scripts dentro dela serão executados em ordem alfabética.
      - ./initdb:/docker-entrypoint-initdb.d:ro

volumes:
  mariadb_data: {}