services:
  - type: web
    name: gerenciador-academia
    env: ruby
    plan: free  # linha para especificar o plano gratuito
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: academia-db
          property: connectionString
      - key: RACK_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: academia-db
    databaseName: academia_jiujitsu
    user: jiujitsu_user
    plan: free